// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oszdzxlflaiowomowiej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zemR6eGxmbGFpb3dvbW93aWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTMwOTYsImV4cCI6MjA3MTY4OTA5Nn0.XgA2shWrzw4B_eyzPBYNeh3BRlKA642SlfZWrsL2zpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});